apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhdh-mcp-proxy
  labels:
    app: rhdh-mcp-proxy
    component: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhdh-mcp-proxy
  template:
    metadata:
      labels:
        app: rhdh-mcp-proxy
        component: proxy
    spec:
      serviceAccountName: rhdh-mcp-proxy
      containers:
      - name: rhdh-mcp-proxy
        image: quay.io/redhat-ai-dev/rhdh-mcp-proxy:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: BACKSTAGE_URL
          valueFrom:
            secretKeyRef:
              name: rhdh-mcp-proxy-secret
              key: backstage-url
        - name: MCP_TOKEN
          valueFrom:
            secretKeyRef:
              name: rhdh-mcp-proxy-secret
              key: mcp-token
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true 
