apiVersion: v1
kind: Service
metadata:
  name: rhdh-mcp-proxy
  labels:
    app: rhdh-mcp-proxy
    component: proxy
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: rhdh-mcp-proxy
